

esiea_platform:
    resource: "@ESIEAPlatformBundle/Resources/config/routing.yml"
    prefix:   /



esiea_core:
    resource: "@ESIEACoreBundle/Resources/config/routing.yml"
#A changer si l'on souhaite changer le paths
