# src/ESIEA/PlatformBundle/Resources/config/routing.yml




esiea_platform_home:

    path:      /platform

    defaults:

        _controller: ESIEAPlatformBundle:Advert:index

    

esiea_platform_view:

    path:      /platform/advert/{id}

    defaults:

        _controller: ESIEAPlatformBundle:Advert:view

    

esiea_platform_add:

    path:      /platform/add

    defaults:

        _controller: ESIEAPlatformBundle:Advert:add



