# src/ESIEA/PlatformBundle/Resources/config/routing.yml




esiea_platform_home:

    path:      /platform

    defaults:

        _controller: ESIEAPlatformBundle:Advert:index

    

esiea_platform_view:

    path:      /advert/{id}

    defaults:

        _controller: ESIEAPlatformBundle:Advert:view
    requirements:
        id: \d+ #Récupération des annonces




esiea_platform_view_slug:

    path:      /{year}/{slug}.{format}

    defaults:
        _controller: ESIEAPlatformBundle:Advert:viewSlug
        format: html
    requirements:
        year: \d{4}
        format: html|xml

#Routage des pages
esiea_platform_home: 

    path:      /{page}

    defaults:

        _controller: ESIEAPlatformBundle:Advert:index

        page:        1

    requirements:

        page: \d*

esiea_platform_add:
    path:      /add
    defaults:
        _controller: ESIEAPlatformBundle:Advert:add

esiea_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: ESIEAPlatformBundle:Advert:edit
    requirements:
        id: \d+

esiea_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: ESIEAPlatformBundle:Advert:delete
    requirements:
        id: \d+

