# src/ESIEA/PlatformBundle/Resources/config/routing.yml
#RecetteAction
esiea_platform_home:
    path:      /{page}
    defaults:
        _controller: ESIEAPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*
    
esiea_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: ESIEAPlatformBundle:Advert:view
    requirements:
        id: \d+

esiea_platform_add:
    path:      /add
    defaults:
        _controller: ESIEAPlatformBundle:Advert:add

esiea_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: ESIEAPlatformBundle:Advert:edit
    requirements:
        id: \d+

esiea_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: ESIEAPlatformBundle:Advert:delete
    requirements:
        id: \d+



esiea_platform_faq:
    path:     /faq
    defaults:
        _controller: ESIEAPlatformBundle:Order:faq

#DeliveryAction
esiea_platform_delivery:
    path:     /delivery/
    defaults:
        _controller: ESIEAPlatformBundle:Order:delivery

esiea_platform_viewdelivery:
    path:     /viewdelivery/{id}
    defaults:
        _controller: ESIEAPlatformBundle:Order:viewdelivery
    requirements:
        id: \d+

esiea_platform_updatedelivery:
    path:      /updatedelivery/{id}
    defaults:
        _controller: ESIEAPlatformBundle:Order:updatedelivery
    requirements:
        id: \d+

#PaymentAction
esiea_platform_payment:
    path:     /payment/
    defaults:
        _controller: ESIEAPlatformBundle:Order:payment

esiea_platform_viewpayment:
    path:      /viewpayment/{id}
    defaults:
        _controller: ESIEAPlatformBundle:Order:viewpayment
    requirements:
        id: \d+

esiea_platform_updatepayment:
    path:     /updatepayment/{id}
    defaults:
        _controller: ESIEAPlatformBundle:Order:updatepayment
    requirements:
        id: \d+
#Récapitulatif de la commande#
esiea_platform_recap_order:
    path:     /recap_order/{id}
#    path:     /recap_order/
    defaults:
        _controller: ESIEAPlatformBundle:Order:recap_order
#   requirements:
        id: \d+

esiea_platform_order_success:
    path:      /order_success/{id}
    defaults:
        _controller: ESIEAPlatformBundle:Order:ordersuccess
    requirements:
        id: \d+