services:
#    esiea_platform.antispam:
#        class: ESIEA\PlatformBundle\Antispam\ESIEAAntispam
#        arguments:
#            - "@mailer"
#            - %locale%
#            - 50
#    esiea_platform.example:
#        class: ESIEA\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
